previewsEnabled: true
services:
  # A Docker web service
  - type: web
    name: undb
    env: docker
    repo: https://github.com/undb-xyz/undb.git
    region: singapore
    plan: standard
    rootDir: .
    numInstances: 0
    healthCheckPath: /health
    envVars:
      - key: PUBLIC_UNDB_ADMIN_EMAIL
        value: test@example.com
      - key: PUBLIC_UNDB_ADMIN_PASSWORD
        value: 123456
      - key: PUBLIC_UNDB_IS_DEMO
        value: 'true'
      - key: PUBLIC_UNDB_ANALYTICS_DOMAIN
        value: demo.undb.xyz
      - key: UNDB_SEED
        value: 'true'
